# Example Site settings

google_analytics: UA-155988625-1

title: Chun

header_pages:
  - about.md
  - read.md
#  - translate.md
#  - think.md


footer: 'follow me on <a href="https://www.instagram.com/chun_app/" target="_blank">Instagram</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

